### PR TITLE
BUGFIX gcpkms support 

### PR DESCRIPTION
**Pull request by mattclegg**
Seems [this](https://github.com/lokkersp/terraform-provider-sops/pull/3#issue-1425905865) wasn't enough :(

### CODE REVIEW

**Comment by mattclegg** [comment]
@lokkersp I've confirmed this is now working for me locally

**Comment by mattclegg** [comment]
Thanks for merging @lokkersp 
Would you mind triggering a tag release so it's available from the registry please?

**Comment by mattclegg** [comment]
I've created a release for this now in the registry; https://registry.terraform.io/providers/mattclegg/sops/latest

**Comment by x0ddf** [comment]
> Thanks for merging @lokkersp Would you mind triggering a tag release so it's available from the registry please?

Yes, sure. Busy days :)

**Pull request merged**
